Repository ZapeeoSheikh/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Responsive Login Page
  index.html
  style.css
Labels: hacktoberfest-accepted

#5 Create RotateArray.js
  RotateArray.js
Labels: good first issue, hacktoberfest-accepted

#4 Quiz app javascript
  quizapp/app.js
  quizapp/index.html
  quizapp/quiz.html
  quizapp/result.html
  quizapp/style.css
  quizapp/trophy.png
Labels: enhancement, hacktoberfest-accepted

#8 added general-letter format
  general-letter/index.html
  general-letter/styles.css
Labels: hacktoberfest-accepted

#7 Responsive restaurant website
  restaurant-website/about.html
  restaurant-website/contact.html
  restaurant-website/images/about.jpg
  restaurant-website/images/card1.jpg
  restaurant-website/images/card2.jpg
  restaurant-website/images/card3.jpg
  restaurant-website/images/chef1.jpg
  restaurant-website/images/chef2.jpg
  restaurant-website/images/chef3.jpg
  restaurant-website/images/contact.jpg
  restaurant-website/images/dish1.jpg
  restaurant-website/images/dish2.jpg
  restaurant-website/images/dish3.jpg
  restaurant-website/images/dish4.jpg
  restaurant-website/images/dish5.jpg
  restaurant-website/images/dish6.jpg
  restaurant-website/images/menu.jpg
  restaurant-website/images/menu1.jpg
  restaurant-website/images/menu10.jpg
  restaurant-website/images/menu11.jpg
  restaurant-website/images/menu12.jpg
  restaurant-website/images/menu13.jpg
  restaurant-website/images/menu2.jpg
  restaurant-website/images/menu4.jpg
  restaurant-website/images/menu5.jpg
  restaurant-website/images/menu6.jpg
  restaurant-website/images/menu7.jpg
  restaurant-website/images/menu8.jpg
  restaurant-website/images/menu9.jpg
  restaurant-website/images/slider1.jpg
  restaurant-website/images/slider2.jpg
  restaurant-website/images/slider3.jpg
  restaurant-website/images/slider4.jpg
  restaurant-website/images/slider5.jpg
  restaurant-website/images/slider5.webp
  restaurant-website/index.html
  restaurant-website/menu.html
  restaurant-website/style.css
Labels: hacktoberfest-accepted

#14 Added shopping list app
  Shopping_list/index.html
  Shopping_list/script.js
  Shopping_list/style.css
Labels: hacktoberfest-accepted

#10 Added JavaScript Beginner Project - Word Length Counter
  Word-Length-Counter-JS-Project/index.css
  Word-Length-Counter-JS-Project/index.html
Labels: hacktoberfest-accepted

#17 + added quotes api
  Random-Quote-Generator/index.css
  Random-Quote-Generator/index.html
Labels: help wanted, hacktoberfest-accepted

#19 Complete Youtube Video Downlaoder Web App
  .gitignore
  Procfile
  Youtube-Video-Downloader/.gitignore
  Youtube-Video-Downloader/Procfile
  Youtube-Video-Downloader/app.py
  Youtube-Video-Downloader/requirements.txt
  Youtube-Video-Downloader/static/Robots.txt
  Youtube-Video-Downloader/static/Script/ajax.js
  Youtube-Video-Downloader/static/Script/index.js
  Youtube-Video-Downloader/static/Script/index.min.js
  Youtube-Video-Downloader/static/Style/index.css
  Youtube-Video-Downloader/static/Style/index.min.css
  Youtube-Video-Downloader/static/icon.svg
  Youtube-Video-Downloader/static/sitemap.xml
  Youtube-Video-Downloader/templates/about.html
  Youtube-Video-Downloader/templates/download.html
  Youtube-Video-Downloader/templates/error.html
  Youtube-Video-Downloader/templates/layout.html
  Youtube-Video-Downloader/templates/page_not_found.html
  Youtube-Video-Downloader/templates/youtube.html
Labels: enhancement, hacktoberfest-accepted

#15 added tic tac toe game
  Tic-Tac-Toe_game/index.html
  Tic-Tac-Toe_game/script.js
  Tic-Tac-Toe_game/style.css
  Tic-Tac-Toe_game/tic.jpg
Labels: enhancement, hacktoberfest-accepted

#16 HTML, JS & Bootstrap
  Header-Color-Changing/index.html
Labels: enhancement, hacktoberfest-accepted

#21 added snake game
  Snake-Game/SnakeMusic.mp3
  Snake-Game/click.wav
  Snake-Game/food.wav
  Snake-Game/gameover.wav
  Snake-Game/index.js
  Snake-Game/snake.html
  Snake-Game/style.css
Labels: duplicate
